Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2019-11, with the labels that each got.

#156 CI improvements
  Jenkinsfile
  pom.xml
  src/it/JENKINS-45740-metadata/invoker.properties
  src/it/JENKINS-58771-packaged-plugins/invoker.properties
  src/it/assemble-dependencies-as-jpi/invoker.properties
  src/it/assemble-dependencies/invoker.properties
  src/it/bad-bundle/invoker.properties
  src/it/bundle-fails-optional-conflict/invoker.properties
  src/it/bundle-with-optional-deps/invoker.properties
  src/it/compile-fork-it/invoker.properties
  src/it/compile-it/invoker.properties
  src/it/parent-3x/invoker.properties
  src/it/process-jar/invoker.properties
  src/it/snapshot-version-override/invoker.properties
  src/it/verify-it/invoker.properties
Labels: internal

#158 Update parent POM
  pom.xml
Labels: dependencies

#157 Upgrade Jetty from 9.4.5.v20170502 to 9.4.22.v20191022
  pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Labels: dependencies

#162 Fix typo in change log hpi property
  src/it/JENKINS-45740-metadata/pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
Labels: bug
