Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2019-08, with the labels that each got.

#132 Align versions of Maven and Maven Plugin Tools dependencies
  pom.xml
Labels: dependencies

#137 Add title to README.md file
  README.md
Labels: documentation

#68 [JENKINS-45740] - Support injecting extra metadata into the Plugin manifest
  src/it/JENKINS-45740-metadata/invoker.properties
  src/it/JENKINS-45740-metadata/pom.xml
  src/it/JENKINS-45740-metadata/src/main/resources/index.jelly
  src/it/JENKINS-45740-metadata/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
Labels: enhancement
