Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2020-10, with the labels that each got.

#195 Fix `list-plugin-dependencies` documentation, not all plugins are listed by the mojo
  src/main/java/org/jenkinsci/maven/plugins/hpi/ListPluginDependenciesMojo.java
Labels: bug

#191 Add `validate-hpi` which checks core version for dependencies before packaging
  src/it/check-core-version-failure/invoker.properties
  src/it/check-core-version-failure/pom.xml
  src/it/check-core-version-failure/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
  src/it/check-core-version-failure/verify.groovy
  src/it/check-core-version-success/invoker.properties
  src/it/check-core-version-success/pom.xml
  src/it/check-core-version-success/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
  src/main/resources/META-INF/plexus/components.xml
Labels: enhancement

#198 `validate-hpi` needs test-scope dependency resolution for these plugin dependencies using test scope
  src/it/check-core-version-failure/pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
Labels: bug

#199 Switch from dependabot.com to GitHub-native Dependabot
  .github/dependabot.yml
Labels: chore
