Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2021-11, with the labels that each got.

#244 Use the project’s basedir to run `git rev-parse HEAD`
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Labels: bug

#246 Remove `bundle-plugins` goal
  src/it/bad-bundle/invoker.properties
  src/it/bad-bundle/pom.xml
  src/it/bundle-fails-optional-conflict/invoker.properties
  src/it/bundle-fails-optional-conflict/pom.xml
  src/it/bundle-with-optional-deps/invoker.properties
  src/it/bundle-with-optional-deps/pom.xml
  src/it/bundle-with-optional-deps/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/BundlePluginsMojo.java
Labels: removed

#247 Maven 3 upgrade
  pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractDependencyGraphTraversingMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/JarMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
Labels: dependencies

#249 Refresh build metadata
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: internal

#250 Miscellaneous code cleanup
  src/main/java/hudson/Extension.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/Artifacts.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AssembleDependenciesMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/CollectionUtils.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ConsoleScanner.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/JarMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ListPluginDependenciesMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/PluginWorkspaceMapImpl.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/PropertyUtils.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ReservedName.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
Labels: internal

#251 Ensure implementation and specification entries are present in `MANIFEST.MF`
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
Labels: bug
