Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2021-06, with the labels that each got.

#223 Updating old wiki link
  src/site/apt/index.apt
Labels: documentation

#222 Deleting obsolete `<ciManagement>` section
  pom.xml
Labels: chore

#225 Log artifactId in validate mojo on IOException
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
Labels: enhancement
