Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2021-12, with the labels that each got.

#253 Add missing `@Override` and `@Deprecated` annotations
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AssembleDependenciesMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/CollectionUtils.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ConsoleScanner.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/JarMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ListPluginDependenciesMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
Labels: skip-changelog

#254 Remove unneeded `CollectionUtils` class
  src/main/java/org/jenkinsci/maven/plugins/hpi/CollectionUtils.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/JettyAndServletApiOnlyClassLoader.java
Labels: skip-changelog

#257 Move old changelog to archive link
  README.md
Labels: documentation

#258 Link to `/doc/developer/plugin-development/mark-a-plugin-incompatible/`
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
Labels: documentation

#260 Fix some (though not all) SpotBugs violations
  pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/PluginWorkspaceMapImpl.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Labels: internal

#259 Fix some (though not all) Enforcer warnings
  pom.xml
Labels: internal

#261 Bump `support-log-formatter` from 1.0 to 1.1
  pom.xml
Labels: dependencies, java

#262 Bump `version-number` from 1.8 to 1.9
  pom.xml
Labels: dependencies, java

#263 Bump Stapler from 1593.v0e838714faae to 1612.v2a13b906bf3a
  pom.xml
Labels: dependencies, java

#264 Bump `jetty-maven-plugin` from 9.4.32.v20200930 to 9.4.44.v20210927
  pom.xml
Labels: dependencies, java

#265 Remove unneeded `PropertyUtils` class
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/PropertyUtils.java
Labels: removed

#267 Remove duplicate methods
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Labels: internal

#266 Use `mojo-executor`
  pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Labels: internal

#268 Fix deprecated `@Component` annotation warnings
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RecordCoreLocationMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
Labels: internal

#269 Remove `hpi:create`
  src/main/java/org/jenkinsci/maven/plugins/hpi/CreateMojo.java
  src/site/apt/index.apt
Labels: removed

#274 Adopt POM Code Convention
  pom.xml
Labels: internal

#275 Sort dependencies
  pom.xml
Labels: internal
