Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2022-02, with the labels that each got.

#289 Ignore Jetty 10.x and 11.x
  .github/dependabot.yml
Labels: dependencies, java

#291 Remove usages of `StringUtils`
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
Labels: skip-changelog

#297 Include classifier when computing final name
  src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
Labels: bug

#295 Fix `OS_OPEN_STREAM` SpotBugs violation
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
Labels: chore

#294 Fix `RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUE` SpotBugs violation
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Labels: chore

#296 Fix `RV_RETURN_VALUE_IGNORED_BAD_PRACTICE` SpotBugs violations
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestHplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Labels: chore

#300 Revert support targetPath property for webResources
  src/it/JENKINS-64408-packaged-webresources/invoker.properties
  src/it/JENKINS-64408-packaged-webresources/pom.xml
  src/it/JENKINS-64408-packaged-webresources/src/main/resources/index.jelly
  src/it/JENKINS-64408-packaged-webresources/src/main/webapp/standard-resource.txt
  src/it/JENKINS-64408-packaged-webresources/src/main/webapp2/non-standard-resource-in-subdir.txt
  src/it/JENKINS-64408-packaged-webresources/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Labels: bug

#301 Record `maven-invoker-plugin` failures via `junit` rather than console
  Jenkinsfile
  pom.xml
  src/it/JENKINS-45740-metadata/invoker.properties
  src/it/JENKINS-58771-packaged-plugins-2/invoker.properties
  src/it/JENKINS-58771-packaged-plugins-3/invoker.properties
  src/it/JENKINS-58771-packaged-plugins/invoker.properties
  src/it/assemble-dependencies-as-jpi/invoker.properties
  src/it/assemble-dependencies/invoker.properties
  src/it/check-core-version-failure/invoker.properties
  src/it/check-core-version-success/invoker.properties
  src/it/compile-fork-it/invoker.properties
  src/it/compile-it/invoker.properties
  src/it/compile-multimodule-it/invoker.properties
  src/it/parent-3x/invoker.properties
  src/it/process-jar/invoker.properties
  src/it/snapshot-version-override/invoker.properties
  src/it/verify-it/invoker.properties
Labels: chore
