Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2022-03, with the labels that each got.

#298 Fine-grained SpotBugs exclusions
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
Labels: skip-changelog

#302 Enforce existence of `src/main/resources/index.jelly`
  src/it/missing-index/invoker.properties
  src/it/missing-index/pom.xml
  src/it/missing-index/src/main/java/org/jenkinsci/tools/hpi/its/X.java
  src/it/missing-index/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
Labels: enhancement

#313 Fixup to #310: remove `icu4j` dep
  pom.xml
Labels: dependencies

#315 Modernize tests
  src/it/JENKINS-45740-metadata/pom.xml
  src/it/JENKINS-58771-packaged-plugins-2/pom.xml
  src/it/JENKINS-58771-packaged-plugins-3/pom.xml
  src/it/JENKINS-58771-packaged-plugins/pom.xml
  src/it/assemble-dependencies-as-jpi/pom.xml
  src/it/assemble-dependencies/pom.xml
  src/it/check-core-version-failure/pom.xml
  src/it/check-core-version-failure/verify.groovy
  src/it/check-core-version-success/pom.xml
  src/it/compile-fork-it/pom.xml
  src/it/compile-it/pom.xml
  src/it/compile-multimodule-it/plugin1/pom.xml
  src/it/compile-multimodule-it/plugin2/pom.xml
  src/it/compile-multimodule-it/pom.xml
  src/it/missing-index/pom.xml
  src/it/parent-3x/pom.xml
  src/it/parent-3x/verify.groovy
  src/it/process-jar/pom.xml
  src/it/process-jar/verify.groovy
  src/it/snapshot-version-override/pom.xml
  src/it/verify-it/pom.xml
Labels: test

#316 Run tests on Java 8 and 11
  Jenkinsfile
Labels: test

#317 Update docs site
  pom.xml
  src/site/apt/index.apt
  src/site/site.xml
Labels: documentation

#319 Improve validation mojo
  pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
Labels: enhancement

#320 Print warning if using deprecated `java.level` with new enough parent POM
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
Labels: enhancement

#322 Dynamically apply `Add-Opens` directives from `MANIFEST.MF`
  src/main/java/org/jenkinsci/maven/plugins/hpi/InitializeMojo.java
  src/main/resources/META-INF/plexus/components.xml
Labels: enhancement

#324 [JENKINS-67974] Java 11 support for MemoryAssert#assertGC
  src/main/java/org/jenkinsci/maven/plugins/hpi/InitializeMojo.java
Labels: enhancement
