Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2022-07, with the labels that each got.

#336 [JENKINS-45047] Support for plugin-to-plugin integration tests
  pom.xml
  src/it/override-test-dependencies-release-failure/invoker.properties
  src/it/override-test-dependencies-release-failure/pom.xml
  src/it/override-test-dependencies-release-failure/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
  src/it/override-test-dependencies-release-failure/verify.groovy
  src/it/override-test-dependencies-smokes/invoker.properties
  src/it/override-test-dependencies-smokes/pom.xml
  src/it/override-test-dependencies-smokes/src/main/resources/index.jelly
  src/it/override-test-dependencies-smokes/src/test/java/test/SampleTest.java
  src/it/override-test-dependencies-smokes/verify.groovy
  src/it/override-test-dependencies-useUpperBounds/invoker.properties
  src/it/override-test-dependencies-useUpperBounds/pom.xml
  src/it/override-test-dependencies-useUpperBounds/src/main/resources/index.jelly
  src/it/override-test-dependencies-useUpperBounds/src/test/java/test/SampleTest.java
  src/it/override-test-dependencies-useUpperBounds/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Labels: enhancement

#355 [JEP-230] Noting deprecation of `jenkins-module` packaging
  src/main/resources/META-INF/plexus/components.xml
Labels: documentation

#366 Ignore self in upper bounds analysis
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Labels: bug

#367 Append to existing properties rather than clobbering them
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Labels: bug

#368 Relax release check
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Labels: bug
