Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2023-05, with the labels that each got.

#481 Fix creation of Custom Wars
  src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
Labels: bug

#478 Handle SNAPSHOT versions in with `overrideWar`
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Labels: bug

#480 IT test for resolve-test-dependencies with snapshots
  pom.xml
  src/it/override-war-with-snapshot/dependant/pom.xml
  src/it/override-war-with-snapshot/dependant/src/main/resources/index.jelly
  src/it/override-war-with-snapshot/dependant/src/test/java/org/jenkins_ci/tools/hpi/its/dependant/DependencyTest.java
  src/it/override-war-with-snapshot/invoker.properties
  src/it/override-war-with-snapshot/verify.groovy
  src/it/override-war-with-snapshot/war-with-plugin/pom.xml
  src/it/override-war-with-snapshot/war-with-plugin/src/main/java/org/jenkins_ci/tools/hpi/its/override_war_with_snapshot/Version.java
  src/it/override-war-with-snapshot/war-with-plugin/src/main/resources/index.jelly
Labels: chore

#489 Remove unused dependencies
  pom.xml
Labels: dependencies, java

#494 Satisfy `ReadOnlyPluginParametersValidator`
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Labels: bug
