Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2023-09, with the labels that each got.

#535 Support Ubuntu version of OpenJDK in tests
  src/it/warResources/src/main/webResource-filtering/help-globalConfig.html
  src/it/warResources/verify.groovy
Labels: test, skip-artifact-caching-proxy

#536 Rename integration test from camel case to kebab case
  src/it/war-resources/invoker.properties
  src/it/war-resources/pom.xml
  src/it/war-resources/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
  src/it/war-resources/src/main/resources/index.jelly
  src/it/war-resources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/config.jelly
  src/it/war-resources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/global.jelly
  src/it/war-resources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/help-name.html
  src/it/war-resources/src/main/resources/org/jenkinsci/tools/hpi/its/Messages.properties
  src/it/war-resources/src/main/webResource-filtering/help-globalConfig.html
  src/it/war-resources/verify.groovy
Labels: test, skip-artifact-caching-proxy

#537 Restore build stability
  Jenkinsfile
  pom.xml
Labels: skip-changelog

#539 Upgrade plugin parent POM in test suite
  src/it/JENKINS-45740-metadata/pom.xml
  src/it/JENKINS-58771-packaged-plugins-2/pom.xml
  src/it/JENKINS-58771-packaged-plugins-3/pom.xml
  src/it/JENKINS-58771-packaged-plugins/pom.xml
  src/it/assemble-dependencies-as-jpi/pom.xml
  src/it/assemble-dependencies/pom.xml
  src/it/check-core-version-failure/pom.xml
  src/it/check-core-version-success/pom.xml
  src/it/compile-fork-it/pom.xml
  src/it/compile-it/pom.xml
  src/it/compile-multimodule-it/pom.xml
  src/it/java-level/pom.xml
  src/it/jenkins-version/pom.xml
  src/it/metadata-it/pom.xml
  src/it/minimum-java-version/pom.xml
  src/it/missing-index/pom.xml
  src/it/override-test-dependencies-release-failure/pom.xml
  src/it/override-test-dependencies-smokes/pom.xml
  src/it/override-test-dependencies-useUpperBounds/pom.xml
  src/it/override-war-with-snapshot/dependant/pom.xml
  src/it/override-war-with-snapshot/war-with-plugin/pom.xml
  src/it/parent-4x/pom.xml
  src/it/process-jar/pom.xml
  src/it/process-test-classes/pom.xml
  src/it/snapshot-version-override/pom.xml
  src/it/verify-it/pom.xml
  src/it/war-resources/pom.xml
Labels: test

#527 Test on Java 21
  Jenkinsfile
Labels: chore

#543 Remove unnecessary version
  pom.xml
Labels: skip-changelog
