Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2023-03, with the labels that each got.

#440 set maven libs according to consumers
  .github/dependabot.yml
  pom.xml
Labels: dependencies, maintenance

#445 Support directories with spaces
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java
Labels: bug

#447 Drop support for 2.332.x and 2.346.x for BOM test suite
  src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
Labels: internal

#448 Remove unnecessary managed dependency
  pom.xml
Labels: internal

#450 integration test for extra warResources
  src/it/warResources/invoker.properties
  src/it/warResources/pom.xml
  src/it/warResources/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
  src/it/warResources/src/main/resources/index.jelly
  src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/config.jelly
  src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/global.jelly
  src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/help-name.html
  src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/Messages.properties
  src/it/warResources/src/main/webResource-filtering/help-globalConfig.html
  src/it/warResources/verify.groovy
Labels: chore

#451 fix filtering of web resources using system properties and escaping
  pom.xml
  src/it/warResources/src/main/webResource-filtering/help-globalConfig.html
  src/it/warResources/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Labels: bug, breaking

#453 [JENKINS-62658] Multi-module Jenkins plugins fail `mvn process-test-classes`
  src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
Labels: bug

#459 Test against latest plugin parent POM
  src/it/JENKINS-45740-metadata/pom.xml
  src/it/JENKINS-58771-packaged-plugins-2/pom.xml
  src/it/JENKINS-58771-packaged-plugins-3/pom.xml
  src/it/JENKINS-58771-packaged-plugins/pom.xml
  src/it/assemble-dependencies-as-jpi/pom.xml
  src/it/assemble-dependencies/pom.xml
  src/it/check-core-version-failure/pom.xml
  src/it/check-core-version-success/pom.xml
  src/it/compile-fork-it/pom.xml
  src/it/compile-it/pom.xml
  src/it/compile-multimodule-it/pom.xml
  src/it/java-level/pom.xml
  src/it/jenkins-version/pom.xml
  src/it/minimum-java-version/pom.xml
  src/it/missing-index/pom.xml
  src/it/override-test-dependencies-release-failure/pom.xml
  src/it/override-test-dependencies-smokes/pom.xml
  src/it/override-test-dependencies-useUpperBounds/pom.xml
  src/it/parent-4x/pom.xml
  src/it/process-jar/pom.xml
  src/it/snapshot-version-override/pom.xml
  src/it/verify-it/pom.xml
  src/it/warResources/pom.xml
Labels: test

#454 Resolve test dependencies in parallel
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Labels: enhancement

#460 Add test for JENKINS-62658
  src/it/process-test-classes/invoker.properties
  src/it/process-test-classes/pom.xml
  src/it/process-test-classes/process-test-classes-bar/pom.xml
  src/it/process-test-classes/process-test-classes-bar/src/main/resources/index.jelly
  src/it/process-test-classes/process-test-classes-foo/pom.xml
  src/it/process-test-classes/process-test-classes-foo/src/main/java/HelloWorld.java
  src/it/process-test-classes/process-test-classes-foo/src/main/resources/index.jelly
  src/it/process-test-classes/verify.groovy
Labels: test

#462 Log more artifact metadata in `TestDependencyMojo`
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Labels: internal
