Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2023-06, with the labels that each got.

#499 Remove use of Maven Wagon
  .github/workflows/site.yml
  pom.xml
Labels: documentation

#500 Restore mojo docs
  pom.xml
Labels: documentation

#501 remove Plugin-Module manifest entry
  src/it/metadata-it/verify.groovy
  src/it/verify-it/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
Labels: removed

#505 Remove use of Plexus Component Descriptor XML
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/AbstractJenkinsModuleArtifactHandler.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/AbstractJenkinsModuleLifecycleMappingProvider.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/AbstractLifecycleMappingProvider.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/ExecutableWarArtifactHandler.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/HpiArtifactHandler.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/HpiLifecycleMappingProvider.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/JenkinsModuleArtifactHandler.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/JenkinsModuleLifecycleMappingProvider.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/JmArtifactHandler.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/JmLifecycleMappingProvider.java
  src/main/resources/META-INF/plexus/components.xml
Labels: internal

#506 Migrate from `maven-artifact-transfer` to direct use of Resolver API
  pom.xml
  src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java
  src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
Labels: internal

#507 [JENKINS-68860] `hpi:run` does not add `Add-Opens` directives for Java 17
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Labels: bug
