Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2024-03, with the labels that each got.

#585 Update plugin parent POM
  src/it/JENKINS-45740-metadata/pom.xml
  src/it/JENKINS-58771-packaged-plugins-2/pom.xml
  src/it/JENKINS-58771-packaged-plugins-3/pom.xml
  src/it/JENKINS-58771-packaged-plugins/pom.xml
  src/it/assemble-dependencies-as-jpi/pom.xml
  src/it/assemble-dependencies/pom.xml
  src/it/check-core-version-failure/pom.xml
  src/it/check-core-version-success/pom.xml
  src/it/compile-fork-it/pom.xml
  src/it/compile-it/pom.xml
  src/it/compile-multimodule-it/pom.xml
  src/it/ensure-java-level-marker-11-migration/pom.xml
  src/it/ensure-java-level-marker-11/pom.xml
  src/it/java-level/pom.xml
  src/it/jenkins-version/pom.xml
  src/it/metadata-it/pom.xml
  src/it/minimum-java-version/pom.xml
  src/it/missing-index/pom.xml
  src/it/override-test-dependencies-release-failure/pom.xml
  src/it/override-test-dependencies-smokes/pom.xml
  src/it/override-test-dependencies-useUpperBounds/pom.xml
  src/it/override-war-with-snapshot/dependant/pom.xml
  src/it/override-war-with-snapshot/war-with-plugin/pom.xml
  src/it/parent-4x/pom.xml
  src/it/process-jar/pom.xml
  src/it/process-test-classes/pom.xml
  src/it/snapshot-version-override/pom.xml
  src/it/verify-it/pom.xml
  src/it/war-resources/pom.xml
Labels: test

#587 Generates `InjectedTest` in a named package.
  src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
  src/test/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojoTest.java
Labels: enhancement

#588 Exclude recent versions of `org.apache.maven.shared:maven-filtering`
  .github/dependabot.yml
Labels: skip-changelog
