Repository jenkinsci/maven-hpi-plugin, pull requests merged in 2024-09, with the labels that each got.

#652 [JENKINS-73419] Migrate HPI plugin from EE 8 to EE 9
  pom.xml
  src/it/parent-4x/pom.xml
  src/it/parent-4x/src/main/java/test/JustTesting.java
  src/it/parent-4x/verify.groovy
  src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Labels: breaking

#657 Fix "dependencies are in wrong scope" warning
  pom.xml
Labels: bug

#660 Enable Jetty 12 Dependabot updates
  .github/dependabot.yml
Labels: skip-changelog

#661 Clean up `plexus-utils` and `plexus-xml` dependencies
  .github/dependabot.yml
  pom.xml
Labels: internal

#668 Require Apache Maven 3.9.6 or later
  pom.xml
Labels: bug
